# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
       R_BUILD_TAR: tar
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - run: export R_BUILD_TAR=tar; Rscript -e 'print("hello")'

      - name: Installs packages declared in DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Runs R CMD check on an R package
        uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
